# YOLOv5 ğŸš€ by Ultralytics, GPL-3.0 license
# COCO 2017 dataset http://cocodataset.org by Microsoft
# Example usage: python train.py --data coco.yaml
# parent
# â”œâ”€â”€ yolov5
# â””â”€â”€ datasets
#     â””â”€â”€ coco  â† downloads here

train: /content/TK-Datasets/Caras/train
val: /content/TK-Datasets/Caras/test

# Classes
nc: 1  # number of classes
names: ['face']  # class names
